### ISSUE TITLE
Select Dataset: Health

### ISSUE THREAD

**Issue by emily878** [sunlightpolicy/State-Open-Data-Census#17]
Select the one dataset that serves as the touchstone of state-level health data.

**Comment by waldoj** [comment]
I think there are some very important health datasets that we can ignore, because CMS already requires their publication. [Hospital data](https://data.medicare.gov/data/hospital-compare) and [nursing home data](https://data.medicare.gov/data/hospital-compare)—both important, both already happening. Although mental health bed availability is important, I only know of one state—North Carolina—that provides it, and it requires that states actually track bed availability. Birth and death data raises PII concerns (despite that it's already very much public information).

Seems to me that restaurant inspections, medical censure records, and medical licensure are our best candidates.

**Comment by emily878** [comment]
Those are all great - I'd back restaurant inspections because we know it can be used by the developer community.
