### ISSUE TITLE
Select Dataset: Transport and Infrastructure

### ISSUE THREAD

**Issue by emily878** [sunlightpolicy/State-Open-Data-Census#21]
Select the one dataset that serves as the touchstone of state-level transport and infrastructure data.

**Comment by waldoj** [comment]
In my experience, road conditions hit the sweet spot between the "data exists" and "data is useful" axes. Accident locations, construction sites, traffic volume, traffic speed, weather closures, etc. [Virginia's site is a good example](http://www.511virginia.org/)—all of the markers are provided by a handful of JSON feeds.

**Comment by emily878** [comment]
@dsmorgan77 suggested "Safety Statistics (fatal incidents, non-fatal incidents, enforcement)" as a top dataset - what do you think? I love it from the public interest standpoint. 

I'd bet that some rural states do not even collect some of the road condition qualities you mention there - maybe for a later version, or choosing subset of those elements with a safety focus?

**Comment by waldoj** [comment]
I am not aware of rural states being less likely to have 511 systems. Depending on how you measure, either [Vermont](http://vtransmaps.vermont.gov/vtrans511/511live.htm) or [South Dakota](http://www.safetravelusa.com/sd/) is the most rural state in the U.S., and they both have 511 systems. I don't know coverage to be universal, but it's got to be close. Whether they share the _data_ that powers those sites is a different matter.

**Comment by emily878** [comment]
Ah. OK. Still vote to make safety the first dataset, but retract my
suspicion about road incident data.

On Fri, Mar 6, 2015 at 1:11 PM, Waldo Jaquith notifications@github.com
wrote:

> I am not aware of rural states being less likely to have 511 systems.
> Depending on how you measure, either Vermont
> http://vtransmaps.vermont.gov/vtrans511/511live.htm or South Dakota
> http://www.safetravelusa.com/sd/ is the most rural state in the U.S.,
> and they both have 511 systems. I don't know coverage to be universal, but
> it's got to be close. Whether they share the _data_ that powers those
> sites is a different matter.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sunlightpolicy/State-Open-Data-Census/issues/21#issuecomment-77606604
> .

## 

## 

Emily Shaw
National Policy Manager | Sunlight Foundation |
(o) 202-742-1520 x 282 | (c) 207-233-5684
@emilydshaw http://twitter.com/emilydshaw

**Comment by waldoj** [comment]
Let's see if we can get some other people to weigh in on this. I'm nervous about "statistics," because that implies aggregated data. It's interesting to know that accidents were up 25% last year, but it's _really_ valuable to have a dataset for last year, and a dataset for the year before, with per-incident granularity. OTOH, if "statistics" really just means "historical data" then, yes, I would join you and @dsmorgan77 in prioritizing that over real-time data.

**Comment by dsmorgan77** [comment]
OK, let's massage the wording on this, because I think you're all right that my first cut is confusing. :-) I do not want summary-level numbers either. An example of what I am hoping for is available from Open New York: https://data.ny.gov/browse?q=%22motor%20vehicle%20crashes%22&sortBy=relevance&utf8=%E2%9C%93

I think I mean "Reportable Motor Vehicle Crash Details (fatal and non-fatal) and related enforcement data." Not all crashes are reportable/reported, so we need to be a little precise.

Real-time data, like traffic incidents (including construction, blockages, etc.) is also cool, but I'd put that in a different category. Thanks for helping this make more sense!

**Comment by waldoj** [comment]
:+1: Thanks, Dan!
